// GROUP 4: SuperAdmin Module - tenant registry service
// Mock data source standing in for the school tenant API endpoint.

import { SchoolTenant } from '../types';

export const SCHOOL_TENANTS: SchoolTenant[] = [
  { id: 1, name: 'Lincoln College of Science Management & Technology', code: 'LC-SMTS-001', domain: 'lincoln.edu', status: 'active', students: 1240, teachers: 84, storageUsedGb: 139.0, storageQuotaGb: 1000, principalAdmin: 'Dr. Sarah Jenkins', principalEmail: 's.jenkins@lincoln.edu', city: 'Lagos', onboardedOn: '2023-01-14', lastActivity: '4 minutes ago' },
  { id: 2, name: 'St. Augustine Science & Arts Academy', code: 'SA-SMTS-002', domain: 'st-augustine.ac.uk', status: 'active', students: 980, teachers: 65, storageUsedGb: 47.1, storageQuotaGb: 250, principalAdmin: 'Dr. Julian Thorne', principalEmail: 'j.thorne@st-augustine.ac.uk', city: 'Abuja', onboardedOn: '2023-04-02', lastActivity: '22 minutes ago' },
  { id: 3, name: 'Horizon STEM Institute', code: 'HZ-SMTS-003', domain: 'horizon-stem.org', status: 'active', students: 1450, teachers: 96, storageUsedGb: 107.8, storageQuotaGb: 1000, principalAdmin: 'Dr. Fiona Gallagher', principalEmail: 'f.gallagher@horizon-stem.org', city: 'Port Harcourt', onboardedOn: '2023-06-19', lastActivity: '1 hour ago' },
  { id: 4, name: 'Kingsway Polytechnic', code: 'KP-SMTS-004', domain: 'kingswaypoly.ac.uk', status: 'active', students: 820, teachers: 54, storageUsedGb: 60.6, storageQuotaGb: 250, principalAdmin: 'Robert Stirling', principalEmail: 'r.stirling@kingswaypoly.ac.uk', city: 'Ibadan', onboardedOn: '2023-08-07', lastActivity: '3 hours ago' },
  { id: 5, name: 'Cambridge International College', code: 'CIC-SMTS-005', domain: 'cambridge-intl.org', status: 'active', students: 1890, teachers: 120, storageUsedGb: 210.4, storageQuotaGb: 1000, principalAdmin: 'Dr. Victoria Alcott', principalEmail: 'v.alcott@cambridge-intl.org', city: 'Lagos', onboardedOn: '2022-11-23', lastActivity: '12 minutes ago' },
  { id: 6, name: 'Apex Advanced Science Academy', code: 'AASA-SMTS-006', domain: 'apexscience.edu', status: 'active', students: 740, teachers: 48, storageUsedGb: 38.5, storageQuotaGb: 250, principalAdmin: 'Prof. David Mercer', principalEmail: 'd.mercer@apexscience.edu', city: 'Enugu', onboardedOn: '2024-01-30', lastActivity: '5 hours ago' },
  { id: 7, name: 'Oakridge Technical High', code: 'OTH-SMTS-007', domain: 'oakridge.sch.uk', status: 'active', students: 310, teachers: 22, storageUsedGb: 12.5, storageQuotaGb: 50, principalAdmin: 'Eleanor Vance', principalEmail: 'e.vance@oakridge.sch.uk', city: 'Kano', onboardedOn: '2024-03-11', lastActivity: '1 day ago' },
  { id: 8, name: 'Meridian Grammar School', code: 'MGS-SMTS-008', domain: 'meridiangrammar.edu', status: 'active', students: 404, teachers: 29, storageUsedGb: 18.2, storageQuotaGb: 50, principalAdmin: 'Grace Adeyemi', principalEmail: 'g.adeyemi@meridiangrammar.edu', city: 'Benin City', onboardedOn: '2024-05-06', lastActivity: '8 hours ago' },
  { id: 9, name: 'Northgate Institute of Technology', code: 'NIT-SMTS-009', domain: 'northgate-tech.ac.ng', status: 'active', students: 1105, teachers: 72, storageUsedGb: 94.3, storageQuotaGb: 250, principalAdmin: 'Dr. Ibrahim Danladi', principalEmail: 'i.danladi@northgate-tech.ac.ng', city: 'Kaduna', onboardedOn: '2023-09-18', lastActivity: '35 minutes ago' },
  { id: 10, name: 'Silverbrook Girls College', code: 'SGC-SMTS-010', domain: 'silverbrook.sch.ng', status: 'active', students: 288, teachers: 24, storageUsedGb: 9.7, storageQuotaGb: 50, principalAdmin: 'Mrs. Helen Obi', principalEmail: 'h.obi@silverbrook.sch.ng', city: 'Owerri', onboardedOn: '2024-07-22', lastActivity: '2 days ago' },
  { id: 11, name: 'Royal Crest Academy', code: 'RCA-SMTS-011', domain: 'royalcrest.edu.ng', status: 'active', students: 912, teachers: 61, storageUsedGb: 71.9, storageQuotaGb: 250, principalAdmin: 'Dr. Emeka Nwosu', principalEmail: 'e.nwosu@royalcrest.edu.ng', city: 'Abuja', onboardedOn: '2023-11-04', lastActivity: '48 minutes ago' },
  { id: 12, name: 'Brookfield Science Secondary', code: 'BSS-SMTS-012', domain: 'brookfield.sch.ng', status: 'active', students: 352, teachers: 27, storageUsedGb: 21.4, storageQuotaGb: 50, principalAdmin: 'Samuel Okafor', principalEmail: 's.okafor@brookfield.sch.ng', city: 'Jos', onboardedOn: '2024-09-09', lastActivity: '6 hours ago' },
  { id: 13, name: 'Whitestone International School', code: 'WIS-SMTS-013', domain: 'whitestone-intl.org', status: 'active', students: 1620, teachers: 104, storageUsedGb: 168.3, storageQuotaGb: 1000, principalAdmin: 'Dr. Amaka Eze', principalEmail: 'a.eze@whitestone-intl.org', city: 'Lagos', onboardedOn: '2022-08-15', lastActivity: '9 minutes ago' },
  { id: 14, name: 'Hilltop Community College', code: 'HCC-SMTS-014', domain: 'hilltopcc.ac.ng', status: 'active', students: 677, teachers: 44, storageUsedGb: 42.8, storageQuotaGb: 250, principalAdmin: 'Blessing Adeyinka', principalEmail: 'b.adeyinka@hilltopcc.ac.ng', city: 'Ilorin', onboardedOn: '2024-02-26', lastActivity: '4 hours ago' },
  { id: 15, name: 'Greenvale Preparatory', code: 'GVP-SMTS-015', domain: 'greenvaleprep.sch.ng', status: 'active', students: 196, teachers: 18, storageUsedGb: 6.9, storageQuotaGb: 50, principalAdmin: 'Tunde Bakare', principalEmail: 't.bakare@greenvaleprep.sch.ng', city: 'Abeokuta', onboardedOn: '2025-01-13', lastActivity: '3 days ago' },
  { id: 16, name: 'Pinnacle Medical Sciences College', code: 'PMS-SMTS-016', domain: 'pinnaclemed.ac.ng', status: 'active', students: 1380, teachers: 118, storageUsedGb: 196.7, storageQuotaGb: 1000, principalAdmin: 'Prof. Chidi Okonkwo', principalEmail: 'c.okonkwo@pinnaclemed.ac.ng', city: 'Enugu', onboardedOn: '2023-03-08', lastActivity: '17 minutes ago' },
  { id: 17, name: 'Eastbourne Technical Institute', code: 'ETI-SMTS-017', domain: 'eastbourne-tech.ac.ng', status: 'active', students: 845, teachers: 57, storageUsedGb: 66.2, storageQuotaGb: 250, principalAdmin: 'Dr. Yusuf Bello', principalEmail: 'y.bello@eastbourne-tech.ac.ng', city: 'Maiduguri', onboardedOn: '2023-12-01', lastActivity: '1 hour ago' },
  { id: 18, name: 'Clearwater Agricultural College', code: 'CAC-SMTS-018', domain: 'clearwateragric.ac.ng', status: 'active', students: 241, teachers: 21, storageUsedGb: 11.1, storageQuotaGb: 50, principalAdmin: 'Ngozi Udeh', principalEmail: 'n.udeh@clearwateragric.ac.ng', city: 'Makurdi', onboardedOn: '2024-11-17', lastActivity: '14 hours ago' },
  { id: 19, name: 'Crestview Maritime Academy', code: 'CMA-SMTS-019', domain: 'crestview.ac.uk', status: 'active', students: 120, teachers: 12, storageUsedGb: 5.1, storageQuotaGb: 250, principalAdmin: 'Capt. Thomas Hayes', principalEmail: 't.hayes@crestview.ac.uk', city: 'Calabar', onboardedOn: '2026-09-21', lastActivity: '26 minutes ago' },
  { id: 20, name: 'Vanguard Institute of Sciences', code: 'VIS-SMTS-020', domain: 'vanguardsciences.edu', status: 'suspended', students: 640, teachers: 42, storageUsedGb: 67.3, storageQuotaGb: 250, principalAdmin: 'Arthur Pendelton', principalEmail: 'a.pendelton@vanguardsciences.edu', city: 'Warri', onboardedOn: '2023-07-05', lastActivity: '21 days ago' },
  { id: 21, name: 'Lakeside Business School', code: 'LBS-SMTS-021', domain: 'lakesidebiz.ac.ng', status: 'pending', students: 0, teachers: 0, storageUsedGb: 0, storageQuotaGb: 50, principalAdmin: 'Olusegun Adeniyi', principalEmail: 'o.adeniyi@lakesidebiz.ac.ng', city: 'Uyo', onboardedOn: '2026-10-01', lastActivity: 'Awaiting verification' },
];
